name: Build & check compiler error for Android app

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build app with Gradle [debug + release]
        run: ./gradlew build
      - name: Build app bundle [debug]
        run: ./gradlew bundleDebug
      - name: Build app bundle [release]
        run: ./gradlew bundleRelease
      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload Debug Android app bundle artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-debug.aab
          path: app/build/outputs/bundle/debug/app-debug.aab
      - name: Upload Release (unsigned) APK artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Upload Release (unsigned) Android app bundle artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-release-unsigned.aab
          path: app/build/outputs/bundle/release/app-release.aab
